version: '3.8'

services:
  state-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - METRICS_SEPARATE_SERVICE=true
      - TRACING_SEPARATE_SERVICE=true
      - METRICS_SERVICE_URL=http://metrics-service:3001
      - TRACING_SERVICE_URL=http://tracing-service:3002
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    depends_on:
      - metrics-service
      - tracing-service
      - otel-collector

  metrics-service:
    build:
      context: ./services/metrics
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATADOG_ENABLED=true
      - DATADOG_API_KEY=${DATADOG_API_KEY}
      - DATADOG_APP_KEY=${DATADOG_APP_KEY}
      - DATADOG_SERVICE=state-machine-metrics
      - DATADOG_ENV=development
    volumes:
      - metrics-data:/data

  tracing-service:
    build:
      context: ./services/tracing
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
    volumes:
      - tracing-data:/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "14250:14250" # Model
      - "14268:14268" # Collector
      - "14269:14269" # Admin

volumes:
  metrics-data:
  tracing-data: 