global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s
    metrics_path: /metrics

  # TomeConnector Service (if exposing metrics)
  - job_name: 'tome-connector'
    static_configs:
      - targets: ['localhost:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node.js metrics (if using prom-client)
  - job_name: 'nodejs'
    static_configs:
      - targets: ['localhost:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Custom business metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['localhost:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    scrape_timeout: 15s
