version: '3.8'

services:
  fishburger-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - UNLEASH_URL=http://unleash:4242/api
      - UNLEASH_API_KEY=default:development.unleash-insecure-api-token
      - REDIS_URL=redis://redis:6379
      - ENABLE_TRACING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - redis
      - unleash
      - otel-collector
    command: >
      sh -c "./scripts/setup.sh && npm run dev"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  unleash:
    image: unleashorg/unleash-server:4.22.0
    ports:
      - "4242:4242"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/unleash
      - DATABASE_SSL=false
      - INIT_CLIENT_API_TOKENS=default:development.unleash-insecure-api-token
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=unleash
    volumes:
      - postgres-data:/var/lib/postgresql/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.86.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check

  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - "16686:16686" # UI
      - "14250:14250" # model
      - "14268:14268" # collector
      - "14269:14269" # admin

volumes:
  redis-data:
  postgres-data: 